### PR TITLE
Update plugin and test assets to work with latest version of Godot/Escoria/inkgd

### PR DESCRIPTION
**Pull request by cidneyhamilton**
Main changes:
- use up-to-date error logging interface
- remove dependencies (inkgd, escoria-core, etc) from repo. These will quickly become out of date.
- update README
- add animation resources to characters in test project (to avoid throwing errors) 
- translation tag is optional

### CODE REVIEW

**Comment by dploeger** [comment]
Ah, this repo actually includes a working example for the addon. The Addon-zip doesn't include the escoria addons and a bunch of other files (see https://github.com/deep-entertainment/escoria-ink-bridge/blob/main/.gitattributes).

It only includes inkgd which I bundled to have the stable API of the plugin at the state of the bridge. If you think, that's not so optimal, I'd like to talk about it.

If the addon doesn't work with the current version of escoria, you should update the addons in this repository and run the test scenes here.

I hope this makes sense to you. Could I ask you to kindly do that (update the addons in this repo, keep your changes to the bridge and run the test scenes included in the repo)? Thanks. ❤️

**Comment by dploeger** [comment]
(also please use [semantic commit messages](https://github.com/semantic-release/semantic-release) like "fix: did a", "feat: Implemented b")

**Comment by cidneyhamilton** [comment]
> Ah, this repo actually includes a working example for the addon. The Addon-zip doesn't include the escoria addons and a bunch of other files (see https://github.com/deep-entertainment/escoria-ink-bridge/blob/main/.gitattributes).

This makes tons of sense. So normally you'd download a ZIP to use it in a Godot project, and only clone the repo to contribute. I updated the README to reflect this.

> It only includes inkgd which I bundled to have the stable API of the plugin at the state of the bridge. If you think, that's not so optimal, I'd like to talk about it.

inkgd needs to be updated to work with the latest version of inklecate-- see [here](https://github.com/ephread/inkgd/pull/69). I can include the latest version for now.

> If the addon doesn't work with the current version of escoria, you should update the addons in this repository and run the test scenes here.

Done. The test project throws some errors if you try to walk (not sure if this is regression), but otherwise works.

**Comment by dploeger** [comment]
Awesome work. Thanks a lot! 🎁

**Pull request merged**
